/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pusdigg;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author dppra
 */
public class peminjaman_userdimas extends javax.swing.JPanel {
    DefaultTableModel model = new DefaultTableModel();
    Connection conn = null;
    ResultSet rs =null;
    PreparedStatement pst = null;
    String pathGambar;
    
    String username = session.getU_username();
    
    /**
     * Creates new form peminjaman_user
     */
   
  public peminjaman_userdimas() {
     initComponents();

    conn = koneksi.koneksi.koneksiDB();
        nama.setText(username);

        model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 9 ? ImageIcon.class : Object.class;
            }
        };

        jTable1.setModel(model);
        jTable1.setRowHeight(80);

        model.addColumn("Buku_id");
        model.addColumn("Judul");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun_terbit");
        model.addColumn("Stok");
        model.addColumn("Kategori");
        model.addColumn("Rak");
        model.addColumn("Deskripsi");
        model.addColumn("Sampul");

        getData();
}
  
   



void getData() {
    model.setRowCount(0);

    try {
        String sql = "SELECT * FROM buku";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            Object[] obj = new Object[11];

            obj[0] = rs.getInt("buku_id");
            obj[1] = rs.getString("judul");
            obj[2] = rs.getString("penulis");
            obj[3] = rs.getString("penerbit");
            obj[4] = rs.getDate("tahun_terbit");
            obj[5] = rs.getInt("stok");
            obj[6] = rs.getInt("kategori_id");
            obj[7] = rs.getString("rak_buku");
            obj[8] = rs.getString("deskripsi");
             String path = rs.getString("imgsampul");

            // gambar (buat tampilan)
            ImageIcon icon = new ImageIcon(path);
            Image img = icon.getImage().getScaledInstance(60, 80, Image.SCALE_SMOOTH);
            obj[9] = new ImageIcon(img);

            // path asli (buat logic)
            obj[10] = path;

            model.addRow(obj); // ⬅️ INI YANG MEMUNCULKAN DATA
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

 void pilihData() {
    int i = jTable1.getSelectedRow();
    judul.setText(model.getValueAt(i, 1).toString());
}
 
 private void bersih() {
    // field input user
    judul.setText("");
    jumlah_dipinjam.setText("");

    // reset pilihan tabel
    jTable1.clearSelection();

    // fokus balik ke tabel / judul
    judul.requestFocus();
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        cmb_cari = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jumlah_dipinjam = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nama = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul", "Penulis", "Penerbit" }));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name Peminjam");

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Jumlah Pinjam");

        jButton2.setText("Pinjam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlah_dipinjam)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jumlah_dipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
pilihData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                     

    int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih buku terlebih dahulu!");
        return;
    }

    if (jumlah_dipinjam.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan jumlah pinjam!");
        return;
    }

    try {
        int userId = Integer.parseInt(session.getU_id());
        int bukuId = Integer.parseInt(model.getValueAt(row, 0).toString());
        int jumlah = Integer.parseInt(jumlah_dipinjam.getText());

        // 🔴 BATAS MAKSIMAL 3 BUKU
        PreparedStatement cek = conn.prepareStatement(
            "SELECT COUNT(*) FROM peminjaman " +
            "WHERE user_id = ? AND status IN ('pending','dipinjam')"
        );
        cek.setInt(1, userId);
        ResultSet rsc = cek.executeQuery();

        if (rsc.next()) {
            int totalPinjam = rsc.getInt(1);

            if (totalPinjam + jumlah > 3) {
                JOptionPane.showMessageDialog(this,
                    "❌ Maksimal peminjaman 3 buku per user!");
                return;
            }
        }

        // ✅ SIMPAN PEMINJAMAN
        PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO peminjaman " +
            "(user_id, buku_id, jumlah_pinjam, tanggal_pinjam, status, denda) " +
            "VALUES (?, ?, ?, NOW(), 'pending', 0)"
        );

        ps.setInt(1, userId);
        ps.setInt(2, bukuId);
        ps.setInt(3, jumlah);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,
            "📩 Peminjaman berhasil diajukan\nMenunggu verifikasi admin");

        jumlah_dipinjam.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String sql = "";
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Menghapus data lama dari tabel
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            if (cmb_cari.getSelectedIndex() == 0) {
                sql = "SELECT * FROM buku WHERE Judul LIKE ?";
            } else if (cmb_cari.getSelectedIndex() == 1) {
                sql = "SELECT * FROM buku WHERE Penulis LIKE ?";
            } else if (cmb_cari.getSelectedIndex() == 2) {
                sql = "SELECT * FROM buku WHERE Penerbit LIKE ?";
            }
                
            // Menyiapkan statement SQL
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txt_cari.getText() + "%");

            rs = pst.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[10];
                 row[0] = rs.getInt("buku_id");
            row[1] = rs.getString("judul");
            row[2] = rs.getString("penulis");
            row[3] = rs.getString("penerbit");
            row[4] = rs.getDate("tahun_terbit");
            row[5] = rs.getInt("stok");
            row[6] = rs.getInt("kategori_id");
            row[7] = rs.getString("rak_buku");
            row[8] = rs.getString("deskripsi");
            row[9] = rs.getString("imgsampul");

                model.addRow(row);
            }

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error saat mencari data: " + e.getMessage()); // Menampilkan pesan error
        }     
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jumlah_dipinjam;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
