/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pusdigg;

/**
 *
 * @author bangkit
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
    // ✅ 1. UNDECORATED HARUS PALING AWAL (sebelum initComponents)
    setUndecorated(true);
    
    // ✅ 2. Baru initComponents (yang memanggil pack() di dalamnya)
    initComponents();
    
    // ✅ 3. Set lokasi tengah
    setLocationRelativeTo(null);
    
    // ✅ 4. Mulai loading
    startLoading();
}
    
    // Method untuk menjalankan thread loading
    private void startLoading() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                // Simulasi proses loading dari 0-100%
                for (int i = 0; i <= 100; i++) {
                    try {
                        // Update progress bar
                        final int progress = i;
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                loading.setValue(progress);
                                
                                // Update text loading secara dinamis
                                if (progress < 30) {
                                    loadingtext.setText("Initializing components...");
                                } else if (progress < 60) {
                                    loadingtext.setText("Loading modules...");
                                } else if (progress < 90) {
                                    loadingtext.setText("Connecting database...");
                                } else {
                                    loadingtext.setText("Starting application...");
                                }
                            }
                        });
                        
                        // Delay 50ms agar terlihat animasi (total ~5 detik)
                        Thread.sleep(50);
                        
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
                
                // Setelah loading selesai, buka form utama dan tutup splash
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        // Ganti MainForm dengan nama form utama Anda
                        new login().setVisible(true);
                        dispose(); // Tutup splash screen
                    }
                });
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelall = new javax.swing.JPanel();
        loadingtext = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        icon = new javax.swing.JLabel();

        // Hapus EXIT_ON_CLOSE karena splash tidak ada tombol close
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Tambahkan ini agar progress bar menampilkan persentase
        loading.setStringPainted(true);
        
        panelall.setPreferredSize(new java.awt.Dimension(1920, 1080));
        panelall.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loadingtext.setText("LOADING..");
        loadingtext.setForeground(java.awt.Color.WHITE); // Pastikan teks terlihat di atas gambar
        panelall.add(loadingtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 970, 400, -1));

        loading.setPreferredSize(new java.awt.Dimension(146, 1080));
        panelall.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1004, 1920, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash/sxt.png"))); // NOI18N
        icon.setText("jLabel1");
        panelall.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        getContentPane().add(panelall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel icon;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel loadingtext;
    private javax.swing.JPanel panelall;
    // End of variables declaration                   
}
