/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spcz;

/**
 *
 * @author bangkit
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        setLocationRelativeTo(null);
        runLoadingAnimation();
    }
// Method untuk menjalankan animasi loading
    private void runLoadingAnimation() {
        Thread loadingThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i <= 100; i++) {
                        final int progress = i;
                        
                        // Update UI di Event Dispatch Thread
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            @Override
                            public void run() {
                                loading.setValue(progress);
                                
                                // Update text sesuai progress
                                if (progress < 25) {
                                    sthx.setText("MEMUAT KOMPONEN...");
                                } else if (progress < 50) {
                                    sthx.setText("MENGHUBUNGKAN DATABASE...");
                                } else if (progress < 75) {
                                    sthx.setText("MENYIAPKAN APLIKASI...");
                                } else if (progress < 100) {
                                    sthx.setText("HAMPIR SELESAI...");
                                } else {
                                    sthx.setText("SELESAI!");
                                }
                            }
                        });
                        
                        // Kecepatan loading (semakin kecil = semakin cepat)
                        Thread.sleep(30);
                    }
                    
                    // Tunggu sebentar sebelum pindah ke form berikutnya
                    Thread.sleep(500);
                    
                    // Pindah ke form berikutnya
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            // Tutup splash screen
                            dispose();
                            
                            // Buka form utama (ganti 'data' dengan nama class form utama Anda)
                            new data().setVisible(true);
                        }
                    });
                    
                } catch (InterruptedException e) {
                    java.util.logging.Logger.getLogger(splash.class.getName()).log(
                        java.util.logging.Level.SEVERE, null, e);
                }
            }
        });
        
        loadingThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mykisah = new javax.swing.JPanel();
        loading = new javax.swing.JProgressBar();
        LSDXT = new javax.swing.JLabel();
        sthx = new javax.swing.JLabel();
        mywaifu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        mykisah.setBackground(new java.awt.Color(255, 0, 255));
        mykisah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mykisah.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1004, 1920, 40));

        LSDXT.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        LSDXT.setText("CONTOH LSDX");
        mykisah.add(LSDXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 620, 290, 100));

        sthx.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        sthx.setText("TUNGGU SEBENTAR..");
        sthx.setPreferredSize(new java.awt.Dimension(170, 40));
        mykisah.add(sthx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 330, 40));

        mywaifu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spcz/sphz/txx1.jpg"))); // NOI18N
        mywaifu.setText("jLabel1");
        mywaifu.setPreferredSize(new java.awt.Dimension(1920, 1080));
        mykisah.add(mywaifu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mykisah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mykisah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LSDXT;
    private javax.swing.JProgressBar loading;
    private javax.swing.JPanel mykisah;
    private javax.swing.JLabel mywaifu;
    private javax.swing.JLabel sthx;
    // End of variables declaration//GEN-END:variables

